const formatData = (infinitief, ovtEnk, ovtMv, vd, eng) => ({infinitief, ovtEnk, ovtMv, vd, eng});

const data = [
	formatData('aankomen', 'kwam aan', 'kwamen aan', 'zijn aangekomen', 'to arrive'),
	formatData('aandoen', 'deed aan', 'deden aan', 'aangedaan', 'to put on'),
	formatData('aannemen', 'nam aan', 'namen aan', 'aangenomen', 'to assume'),
	formatData('aanwerven', 'wierf aan', 'wierven aan', 'aangeworven', 'to enroll'),
	formatData('afwassen', 'waste af', 'wasten af', 'afgewassen', 'to wash'),
	formatData('bakken', 'bakte', 'bakten', 'gebakken', 'to bake'),
	formatData('barsten', 'barstte', 'barstten', 'zijn gebarsten', 'to burst'),
	formatData('bedriegen', 'bedroog', 'bedrogen', 'bedrogen', 'to trick'),
	formatData('beginnen', 'begon', 'begonnen', 'zijn begonnen', 'to begin'),
	formatData('begrijpen', 'begreep', 'begrepen', 'begrepen', 'to understand'),
	formatData('behangen', 'behing', 'behingen', 'behangen', 'to hang'),
	formatData('beschrijven', 'beschreef', 'beschreven', 'beschreven', 'to describe'),
	formatData('besluiten', 'besloot', 'besloten', 'besloten', 'to decide'),
	formatData('bespreken', 'besprak', 'bespraken', 'besproken', 'to discuss'),
	formatData('bevallen', 'beval', 'bevalen', 'bevolen', 'to please'),
	formatData('bevelen', 'beval', 'bevalen', 'bevolen', 'to order'),
	formatData('bewegen', 'bewoog', 'bewogen', 'bewogen', 'to move'),
	formatData('bezoeken', 'bezocht', 'bezochten', 'bezocht', 'to visit'),
	formatData('bezwijken', 'bezweek', 'bezweken', 'zijn bezweken', 'to collapse'),
	formatData('bidden', 'bad', 'baden', 'gebeden', 'to pray'),
	formatData('bieden', 'bood', 'boden', 'geboden', 'to offer'),
	formatData('bijten', 'beet', 'beten', 'gebeten', 'to bite'),
	formatData('binden', 'bond', 'bonden', 'gebonden', 'to bind'),
	formatData('blazen', 'blies', 'bliezen', 'geblazen', 'to blow'),
	formatData('blijken', 'bleek', 'bleken', 'zijn gebleken', 'to prove'),
	formatData('blijven', 'bleef', 'bleven', 'zijn gebleven', 'to stay'),
	formatData('blinken', 'blonk', 'blonken', 'geblonken', 'to blink'),
	formatData('braden', 'braadde', 'braadden', 'gebraden', 'to roast'),
	formatData('breken', 'brak', 'braken', 'gebroken', 'to break'),
	formatData('brengen', 'bracht', 'brachten', 'gebracht', 'to bring'),
	formatData('buigen', 'boog', 'bogen', 'gebogen', 'to bend'),
	formatData('denken', 'dacht', 'dachten', 'gedacht', 'to think'),
	formatData('doen', 'deed', 'deden', 'gedaan', 'to do'),
	formatData('doorbrengen', 'bracht door', 'brachten door', 'doorgebracht', ''),
	formatData('dragen', 'droeg', 'droegen', 'gedragen', 'to wear'),
	formatData('drinken', 'dronk', 'dronken', 'gedronken', 'to drink'),
	formatData('drijven', 'dreef', 'dreven', 'hebben/zijn gedreven', 'to float'),
	formatData('druipen', 'droop', 'dropen', 'hebben/zijn gedropen', 'to drip'),
	formatData('duiken', 'dook', 'doken', 'hebben/zijn gedoken', 'to dive'),
	formatData('dwingen', 'dwong', 'dwongen', 'gedwongen', 'to force'),
	formatData('eten', 'at', 'aten', 'gegeten', 'to eat'),
	formatData('fluiten', 'floot', 'floten', 'gefloten', 'to whistle'),
	formatData('gaan', 'ging', 'gingen', 'zijn gegaan', 'to go'),
	formatData('gelden', 'gold', 'golden', 'gegolden', 'to apply'),
	formatData('genezen', 'genas', 'genazen', 'hebben/zijn genezen', 'to cure'),
	formatData('genieten', 'genoot', 'genoten', 'genoten', 'to enjoy'),
]

export default data;
